Užduotys.

Pirmo lygio.

1. Konvertuokite skaitinių reikšmių sąrašą į vienmatį NumPy masyvą.

Original List: [12.23, 13.32, 100, 36.32] 

One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

2. Sukurkite 10 dydžio nulinį vektorių ir atnaujinkite šeštąją reikšmę iki 11.

3. Sukurkite masyvą, kurio reikšmės svyruoja nuo 12 iki 38.

4. Sukurkite 3x3 matricą, kurios reikšmės svyruoja nuo 2 iki 10.

5. Sukurti vektorių ir apverskite jį keliais būdais (pirmasis elementas tampa paskutiniu).

6. Sukurkite 3x3 matricą, kurios įstrižainė yra vienetai, o visi kiti elementai yra nuliai.

7. Sukurkite 3x3x3 masyvą su atsitiktinėmis reikšmėmis.

8. Sukurkite 10x10 masyvą su atsitiktinėmis reikšmėmis ir suraskite mažiausią ir didžiausią reikšmes.

9. Sukurkite atsitiktinį 30 dydžio vektorių ir raskite vidutinę reikšmę.

10. Sukurkite 10x10 matricą, kurioje elementai ant kraštinių bus lygūs 1, o viduje 0.

11. Sukurkite 10 ilgio vektorių, kurio reikšmės būtų tolygiai paskirstytos tarp 5 ir 50.

12. Sukurkite vektorių, kurių reikšmės svyruoja nuo 15 iki 55, ir atspausdinkite visas reikšmes, išskyrus pirmąją ir paskutinę.

13. Sugeneruokite atsitiktinį skaičių masyve nuo 0 iki 1.

14. Pridėkite reikšmes prie masyvo pabaigos.

Original array: [10, 20, 30] 

After appending values to the end of the array: [10 20 30 40 50 60 70 80 90]

15. Sukurkite tuščią masyvą ir užpildykite masyvą šešetai

In [1]:
import numpy as np

#### 1. Konvertuokite skaitinių reikšmių sąrašą į vienmatį NumPy masyvą.


In [5]:
list = [12.23, 13.32, 100, 36.32]
arr = np.array(list)

print(arr)

[ 12.23  13.32 100.    36.32]


#### 2. Sukurkite 10 dydžio nulinį vektorių ir atnaujinkite šeštąją reikšmę iki 11.


In [6]:
arr = np.zeros(10)
arr[6] = 11
arr

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

#### 3. Sukurkite masyvą, kurio reikšmės svyruoja nuo 12 iki 38

In [8]:
arr = np.arange(12 , 39)
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

#### 4. Sukurkite 3x3 matricą, kurios reikšmės svyruoja nuo 2 iki 10.

In [9]:
matrix = np.arange(2,11).reshape(3,3)
matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

#### 5. Sukurti vektorių ir apverskite jį keliais būdais (pirmasis elementas tampa paskutiniu)

In [17]:
vector = np.arange(10, 21)
vector[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [16]:
np.sort(vector)[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

#### 6. Sukurkite 3x3 matricą, kurios įstrižainė yra vienetai, o visi kiti elementai yra nuliai.