Užduotys.

1. Sukurkite vektorių ir matricą ir juos sudėkite, atimkite, sudauginkite ir padalinkite.

2. Sukurkite 5x5 matricą ir raskite jos didžiausią ir mažiausią reikšmes.

3. Pagal 2 užduoties matricą, suraskite didžiausias ir mažiausias kiekvienos eilutės reikšmes. Paskaičiuokite jų vidurkių skirtumą. (Kad skaičius būtų teigiamas, naudoti galite absolute metodą).

4. Apskaičiuokite 3x3x3 masyvo medianą (naudokite metodą median) ir palyginkite ją su vidurkiu.

5. Statistikos studento A egzaminų rezultatai yra 9,9,7,8,9,10,5,9. Kurso kreditai yra pasiskirstę tokia tvarka: 3,3,6,3,6,3,6,6. Paskaičiuokite studento A kurso vidurkį.

6. Sukurkite matricas 3x4 ir 4x3. Pabandykite jas sudauginti naudojant visus žinomus perkėlimo metodus.

In [3]:
import numpy as np

#### 1. Sukurkite vektorių ir matricą ir juos sudėkite, atimkite, sudauginkite ir padalinkite.


In [13]:
vector = np.array([1,2])
matrix = np.array([[3,4],[5,6]])

In [31]:
print(f'sum of vector and matrix\n{np.add(vector,matrix)}\n')

print(f'substraction of vector and matrix\n{np.subtract(vector,matrix)}\n')

print(f'multiply of vector and matrix\n{np.multiply(vector,matrix)}\n')

print(f'division of vector and matrix\n{np.divide(vector,matrix)}\n')


sum of vector and matrix
[[4 6]
 [6 8]]

substraction of vector and matrix
[[-2 -2]
 [-4 -4]]

multiply of vector and matrix
[[ 3  8]
 [ 5 12]]

division of vector and matrix
[[0.33333333 0.5       ]
 [0.2        0.33333333]]



#### 2. Sukurkite 5x5 matricą ir raskite jos didžiausią ir mažiausią reikšmes.


In [44]:
matrix = np.array(np.random.rand(25)).reshape(5,5)
matrix

array([[0.68879264, 0.17483392, 0.51160713, 0.52909129, 0.16088258],
       [0.13661717, 0.77045105, 0.96981657, 0.23209894, 0.70660331],
       [0.20071517, 0.00174544, 0.82481272, 0.45344732, 0.19429865],
       [0.89857341, 0.14714123, 0.29242571, 0.39075168, 0.62870601],
       [0.19775989, 0.2393388 , 0.22034365, 0.68472445, 0.65924748]])

In [42]:
print(f'max_value = {np.max(matrix)}\nmin_value = {np.min(matrix)}')

max_value = 0.974056193706842
min_value = 0.04122020556600314


#### 3. Pagal 2 užduoties matricą, suraskite didžiausias ir mažiausias kiekvienos eilutės reikšmes. Paskaičiuokite jų vidurkių skirtumą. (Kad skaičius būtų teigiamas, naudoti galite absolute metodą).

In [53]:
max_of_each_row = matrix.max(axis=1)
max_of_each_row

array([0.68879264, 0.96981657, 0.82481272, 0.89857341, 0.68472445])

In [54]:
min_of_each_row = matrix.min(axis=1)
min_of_each_row

array([0.16088258, 0.13661717, 0.00174544, 0.14714123, 0.19775989])

In [56]:
np.average(max_of_each_row)-np.average(min_of_each_row)

0.6845146972534402

#### 4. Apskaičiuokite 3x3x3 masyvo medianą (naudokite metodą median) ir palyginkite ją su vidurkiu.

In [62]:
arr = np.random.random((3,3,3))
arr

array([[[0.96967466, 0.30055042, 0.60286392],
        [0.73122218, 0.36756209, 0.20085532],
        [0.61720836, 0.2402351 , 0.55275811]],

       [[0.55422418, 0.95381983, 0.4310644 ],
        [0.49071363, 0.21372964, 0.02684172],
        [0.04711215, 0.42538938, 0.79923004]],

       [[0.95029755, 0.75775744, 0.78880965],
        [0.26004517, 0.19776786, 0.29315408],
        [0.82589156, 0.56633971, 0.36796077]]])

In [64]:
arr_median = np.median(arr)
arr_median

0.49071362659797657

In [70]:
arr_avg = np.average(arr)
arr_avg

0.5012251454109302

In [69]:
arr_median > arr_avg

False

##### Median of the 3x3x3 array is lower than the average

#### 5. Statistikos studento A egzaminų rezultatai yra 9,9,7,8,9,10,5,9. Kurso kreditai yra pasiskirstę tokia tvarka: 3,3,6,3,6,3,6,6. Paskaičiuokite studento A kurso vidurkį.

In [72]:
results = np.array([9,9,7,8,9,10,5,9])
weights = np.array([3,3,6,3,6,3,6,6])

In [74]:
np.average(results,weights = weights)

8.0